# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4de9fd5342cdffb0d515febb7eb6ff804df0572fc2c1d7497ef47b69e2e181db7e63b9a68a75570bc677d9726f7be7edf42709e49fb5ca7d1c0b6cee9efe281

test:
  secret_key_base: 056cbdbd016c6a5757ae81dba63245ffc926bfac06ad15d40c43de8a177da8559a97f4c631ec91531a01de7d9f98505b41e4b312b3d4e12c9c2da16459588672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
